#-------------------------------------------------------------------------------
# Workflow configuration
#-------------------------------------------------------------------------------

name: "Desktop CI builds (cmake)"
on:
  push:
  pull_request:

#-------------------------------------------------------------------------------
# Define application name & version
#-------------------------------------------------------------------------------

env:
  APP_NAME: "QmlAppTemplate"
  APP_VERSION: "0.6"
  QT_VERSION: "6.5.3"

#-------------------------------------------------------------------------------
# Workflow jobs
#-------------------------------------------------------------------------------

jobs:
  ## GNU/Linux build ###########################################################
  build-linux:
    name: "Linux CI build"
    runs-on: ubuntu-20.04
    steps:
      # Checkout the repository (and submodules)
      - name: Checkout repository (and submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Install Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{env.QT_VERSION}}
          modules: qt5compat

      # Install dependencies (from package manager)
      - name: Install dependencies (from package manager)
        run: |
             sudo apt-get install libgl1-mesa-dev libxkbcommon-x11-dev libx11-xcb-dev libzstd-dev -y;
             sudo apt-get install cmake ninja-build pkgconf libtool appstream -y;

      # Setup env
      - name: Setup env
        run: |
             cmake --version

      # Build application
      - name: Build application
        run: |
             cd build/
             cmake ..
             cmake --build .

      # Deploy application
      - name: Deploy application
        run: |
             ./deploy_linux.sh -c -i -p

      # Upload AppImage
      - name: Upload AppImage
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.APP_NAME}}-${{env.APP_VERSION}}-linux64.AppImage
          path: ${{env.APP_NAME}}*.AppImage

  ## macOS build ###############################################################
  build-mac:
    name: "macOS CI build"
    runs-on: macos-12
    steps:
      # Checkout the repository (and submodules)
      - name: Checkout repository (and submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Install Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{env.QT_VERSION}}
          modules: qt5compat

      # Install dependencies (from package manager)
      - name: Install dependencies (from package manager)
        run: |
             brew install cmake

      # Setup env
      - name: Setup env
        run: |
             cmake --version
             alias nproc="sysctl -n hw.logicalcpu"
             export CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)

      # Build application
      - name: Build application
        run: |
             cd build/
             cmake ..
             cmake --build .

      # Deploy application
      - name: Deploy application
        run: |
             ./deploy_macos.sh -c -p

      # Upload app zip
      - name: Upload app zip
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.APP_NAME}}-${{env.APP_VERSION}}-macOS.zip
          path: bin/${{env.APP_NAME}}-${{env.APP_VERSION}}-macOS.zip

  ## Windows build #############################################################
  build-windows:
    name: "Windows CI build"
    runs-on: windows-2022
    steps:
      # Checkout the repository (and submodules)
      - name: Checkout repository (and submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Configure MSVC
      - name: Configure MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          spectre: true

      # Install Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{env.QT_VERSION}}
          modules: qt5compat

      # Install NSIS (already installed in 'windows-2022')
      #- name: Install NSIS
      #  run: |
      #       Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
      #       scoop bucket add extras
      #       scoop install nsis

      # Setup env
      - name: Setup env
        run: |
             cmake --version

      # Build application
      - name: Build application
        run: |
             cd build/
             cmake .. -G"NMake Makefiles"
             nmake

      # Deploy application
      - name: Deploy application
        run: |
             sh deploy_windows.sh -c -p

      # Upload ZIP
      - name: Upload ZIP
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.APP_NAME}}-${{env.APP_VERSION}}-win64.zip
          path: ${{env.APP_NAME}}-${{env.APP_VERSION}}-win64.zip

      # Upload NSIS installer
      - name: Upload NSIS installer
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.APP_NAME}}-${{env.APP_VERSION}}-win64.exe
          path: ${{env.APP_NAME}}-${{env.APP_VERSION}}-win64.exe
